### ISSUE TITLE
Missing function 'pp.unsupplied_buses()'

### ISSUE THREAD

**Issue by haukebents** [e2nIEE/simbench#11]
When executing the tutorial _simbench_grids_and_basic_usage.ipynb_ in line 13, I get the error message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-50e6aefe7aa1> in <module>
      1 # print number of unsupplied buses
----> 2 unsupplied_buses = pp.unsupplied_buses(net)
      3 len(unsupplied_buses)

AttributeError: module 'pandapower' has no attribute 'unsupplied_buses'
```
Although this is seemingly an issue with the _pandapower_ suite, I thought I'd mention it here since it occured when testing out _SimBench_.

**Comment by SteffenMeinecke** [comment]
Sorry for the late response.
This issue occured since the function unsupplied_buses was not available with pandapower anymore but with pandapower.topology.
But this issue should be fixed with the commit https://github.com/e2nIEE/simbench/commit/2db74a19a98a6e4d63d5fb6b7d0230eb6d205ed9 - see also issue #4.
To fix the error on your machine, please update simbench. If the error persists, please state it here with all your installed python packages and versions.

**Comment by brauliobarahona** [comment]
@SteffenMeinecke I would be handy to also correct line 26 in this tutorial https://github.com/e2nIEE/simbench/blob/master/tutorials/simbench_grids_basics_and_usage.ipynb

**Comment by SteffenMeinecke** [comment]
Thanks @brauliobarahona for raising that issue. It is fixed for the develop branch with commit https://github.com/e2nIEE/simbench/commit/3d9649c47fb45e7395629f9c757bb5e8a37fce24
