### ISSUE TITLE
Can't pass the test due to AssertionError in test_csv_pp_converter.py

### ISSUE THREAD

**Issue by TravisCao** [e2nIEE/simbench#4]
I installed simbench and pandapower with pip but couldn't pass the test when executing the simbench.test.run_all_tests()

The error info is as follows.
![image](https://user-images.githubusercontent.com/35266867/90028648-87629980-dcec-11ea-9e72-ebdf492a313a.png)

ENVIRONMENT:
platform linux -- 
1. Python 3.6.9
2. pytest-6.0.1 
3. pluggy-0.13.1 
4. pandapower=2.2.0
5. newest verison of simbench
6. pandas = 1.1.0

**Comment by SteffenMeinecke** [comment]
Dear TravisCao,
this is due to latest changes within pandapower create_buses API function where other columns than "x" and "y" are not initialized by NaN. As a result in pp2csv one more unique Coordinate is determined.
With the commit https://github.com/e2nIEE/pandapower/pull/864/commits/eba72f1ce2f63d48731fded4f72f671658f55769 this will be fixed with the next pandapower version.
Until then you can use the develope version or an older version of pandapower if you want to run the test. However, as long as you don't want to convert pandapower networks to simbench format (as csv files), you can continue to work with your current versions.

**Comment by TravisCao** [comment]
@SteffenMeinecke Dear SteffenMeinecke,
I uninstalled the official pandapower version from pip and use the develop version with the commit e2nIEE/pandapower@eba72f1. 

However, when I run the tests again, I found another error here, the error info is as follows.

![image](https://user-images.githubusercontent.com/35266867/90115837-3b186780-dd87-11ea-99a5-eb3e3b31149c.png)

It seems that it has something to do with test_extract_grids_from_csv.py file in simbench library.

Could you please send me a packed conda environment? My email address is travisyjcao@gmail.com. Thanks a lot!

**Comment by SteffenMeinecke** [comment]
This also is due to changes of external packages.
With pandapower version 2.3.0 `unsupplied_buses()` ist not available directly with pandapower anymore. It now must be imported via pandapower.topology.
I hope the develop versions of pandapower and simbench are now able to handle the changes of pandas.

**Comment by TravisCao** [comment]
OK.  After using the develop versions of pandapower and simbench, the problem is fixed now. Thanks!
