### ISSUE TITLE
Error while loading simbench network

### ISSUE THREAD

**Issue by harisdtu** [e2nIEE/simbench#6]
Hi,

I'm trying to run a simple test for simbench and just load a network:
![image](https://user-images.githubusercontent.com/25502668/91695894-1dad1100-eb6f-11ea-9f89-94fcad0168e4.png)

However, i get the following error:
![image](https://user-images.githubusercontent.com/25502668/91695835-066e2380-eb6f-11ea-8fa8-098342a0740b.png)

Any ideas? I have the latest package versions installed.

**Comment by SteffenMeinecke** [comment]
This issue is due to changed of pandas.
You probably have pandas 1.x, however, this repository was implemented with a pandas 0.x
-> Please switch to the develop branch of this repository. There, this issue is already fixed.
After fixing issue #2, the develop will be merged into the master. Then you can use the master branch again.

**Comment by SteffenMeinecke** [comment]
The master branch was merged with the develop branch. As a result, this issue should be fixed.
